version: '3.3'

services:
  bookstack-db:
    image: mariadb:10.9
    container_name: bookstack-db
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/bookstack/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somepassword
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=someuser
      - MYSQL_PASSWORD=somepassword
      - MYSQL_INITDB_SKIP_TZINFO=1

  bookstack-app:
    image: ghcr.io/linuxserver/bookstack:v22.04
    container_name: bookstack-app
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/bookstack/app:/config
    links:
      - bookstack-db
    environment:
      - DB_HOST=bookstack-db:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=someuser
      - DB_PASSWORD=somepassword
    ports:
      - 80:80
