version: '3'
services:
    db:
        image: postgres:13
        volumes:
            - /docker/joplin/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=somepassword
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=https://joplin.domain.lol
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=somepassword
            - POSTGRES_DATABASE=postgres
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db