---
version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime
    volumes:
      - <path-to-data>:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3002:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true