version: "3.7"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    command: --schedule "0 0 4 * * *" --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}